version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
    command: >
      sh -c "python proj/manage.py migrate &&
             python proj/manage.py migrate django_celery_beat &&
             python proj/manage.py runserver 0.0.0.0:8000"
  celery:
    build: .
    depends_on:
      - redis
    volumes:
      - .:/app
    working_dir: /app/proj
    command: celery -A proj worker -l INFO
  celery-beat:
    build: .
    depends_on:
      - redis
    volumes:
      - .:/app
    working_dir: /app/proj
    command: celery -A proj beat -l INFO
  redis:
    image: redis:latest